# Generated by Django 4.0.2 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capturecampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('location', models.CharField(default='Forum', max_length=250)),
                ('code', models.CharField(max_length=250)),
            ],
        ),
    ]
